[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]

[workspace.dependencies]
hdi = { git = "https://github.com/holochain/holochain", package = "hdi", rev = "c6bb672d624a884c57ffe588607ffc06aa2f7c74"}
hdk = { git = "https://github.com/holochain/holochain", package = "hdk", rev = "c6bb672d624a884c57ffe588607ffc06aa2f7c74"}
serde = "1"

[workspace.dependencies.files]
path = "dnas/files/zomes/coordinator/files"

[workspace.dependencies.files_integrity]
path = "dnas/files/zomes/integrity/files"
